name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'config/**'
      - 'schemas/**'
      - 'tests/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest jsonschema pydantic psutil arrow
      - name: Run config validation tests
        run: |
          pytest --maxfail=1 --disable-warnings tests/utils/test_config.py
